/* Local visual/interaction QA. Requires a loopback browser-preview.php server and Playwright. */
const {chromium} = require('playwright');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');
(async () => {
    const output = fs.mkdtempSync(path.join(os.tmpdir(), 'governance-editor-qa-'));
    const browser = await chromium.launch({channel: 'msedge', headless: true});
    try {
        const page = await browser.newPage({viewport:{width:1440,height:1000}});
        const errors = []; page.on('pageerror', e => errors.push(e.message));
        const posts = []; page.on('request', r => { if(r.method()==='POST') posts.push(r.url()); });
        let lastResponse = ''; page.on('response', async r => { if(r.request().method()==='POST') lastResponse=(await r.text()).slice(0,1500); });
        await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
        for (const [name, query] of [['quality-dark','?quality&edit'],['quality-light','?quality&edit&light&en'],['availability-dark','?edit'],['availability-light','?edit&light&en']]) {
            const priorPosts = posts.length;
            await page.goto('http://127.0.0.1:8771/' + query);
            await page.locator(name.startsWith('quality') ? '#gov-save:not([disabled])' : '#gav-save:not([disabled])').waitFor();
            assert.equal(await page.locator('header.header-title .gov-action-link').count(), 1, 'Native header owns navigation');
            assert.equal(await page.locator('.gqp-heading,.gav-page-heading').count(), 0, 'No repeated page heading');
            assert.equal(await page.locator('.gov-action-link').evaluate(e => e.getBoundingClientRect().height), 24);
            assert.equal(await page.locator(name.startsWith('quality') ? '#gov-save' : '#gav-save').evaluate(e => e.getBoundingClientRect().height), 24, 'Save retains native size');
            assert.equal(await page.locator(name.startsWith('quality') ? '[data-field=page_name]' : '#gav-timezone').first().evaluate(e => e.getBoundingClientRect().height), 24, 'Compact fields');
            const editor = page.locator(name.startsWith('quality') ? '#gov-config' : '#gav-config');
            const footer = editor.locator(name.startsWith('quality') ? '.gqp-editor-footer' : '.gav-editor-footer');
            assert.equal(await footer.locator('button').count(),1,'Footer has only the persistent save action');
            assert.equal(await editor.locator('.gov-list-actions button').count(),1,'Add belongs to the list');
            assert.equal(await footer.evaluate(e => getComputedStyle(e).position),'static','Footer never overlays fields');
            const requiredInput = page.locator(name.startsWith('quality') ? '[data-field=title]' : '#gav-timezone').first();
            assert.equal(await requiredInput.evaluate(e => getComputedStyle(e.closest('label').querySelector('span'),'::after').content),'" *"','Required fields have a visual marker');
            const surface = editor.locator(name.startsWith('quality') ? '.gqp-page-settings' : '.gav-report-settings').first();
            assert.equal(await surface.evaluate(e => getComputedStyle(e).backgroundColor),name.endsWith('dark') ? 'rgb(43, 43, 43)' : 'rgb(255, 255, 255)','Editors use shared surfaces');
            assert.equal(await surface.evaluate(e => getComputedStyle(e).borderRadius),'0px','Administrative surfaces are flat');
            if (name.startsWith('quality')) {
                const card = page.locator('.gqp-card').first();
                const condition = page.locator('.gqp-condition-dialog');
                const applyCondition = async () => { await condition.locator('.gqp-condition-apply').click(); assert.equal(await condition.count(),0); };
                await card.locator('.gqp-add-condition').click();
                await condition.locator('[data-field=condition_name]').fill('Departamento');
                await condition.locator('[data-field=condition_value]').fill('Banco de Dados');
                await applyCondition();
                await card.locator('.gqp-add-condition').click();
                await condition.locator('[data-field=condition_type]').selectOption('group');
                await condition.locator('[data-field=condition_value]').fill('Equipes');
                await applyCondition();
                const row = card.locator('.gqp-conditions tr').nth(1);
                assert.equal(await card.locator('.gqp-condition-table input,.gqp-condition-table select').count(),0);
                await card.locator('[data-field=type]').selectOption('templates');
                await card.locator('[data-field=template_names]').fill('Linux by Zabbix agent');
                const draft = JSON.parse(await page.locator('#gov-quality-payload').inputValue());
                assert.equal(draft[0].cards[0].selection.conditions.length,2);
                assert.equal(draft[0].cards[0].selection.mode,'all');
                await card.locator('.gqp-add-condition').click();
                await condition.locator('[data-field=condition_type]').selectOption('inventory');
                await condition.locator('[data-field=condition_inventory]').selectOption('location');
                await applyCondition();
                await card.locator('[data-field=selection_mode]').selectOption('custom');
                await card.locator('[data-field=selection_formula]').fill('(A or B) and C');
                assert.equal(JSON.parse(await page.locator('#gov-quality-payload').inputValue())[0].cards[0].selection.formula,'(A or B) and C');
                assert.equal(posts.length,priorPosts,'No automatic preview requests');
                // Catalog opens without a request and adds names, preserving subgroup semantics.
                await row.locator('.gqp-edit-condition').click();
                await condition.locator('[data-field=condition_value]').fill('');
                await condition.locator('.gqp-catalog-open').click();
                const dialog = page.locator('.gqp-catalog-dialog');
                await dialog.waitFor();
                assert.equal(posts.length,priorPosts,'Opening catalog does not query');
                await dialog.locator('input').fill('Equipes');
                await dialog.locator('.gqp-catalog-search').click();
                await dialog.locator('.gqp-catalog-result').click();
                assert.equal(await condition.locator('[data-field=condition_value]').inputValue(),'Equipes');
                assert.equal(await condition.locator('[data-field=condition_subgroups]').inputValue(),'1');
                await applyCondition();
                await card.locator('[data-field=template_names]').fill('');
                await card.locator('[data-for-type=templates] .gqp-catalog-open').click();
                await dialog.locator('input').fill('Linux');
                await dialog.locator('input').press('Enter');
                await dialog.locator('.gqp-catalog-result').waitFor();
                await page.screenshot({path:path.join(output,name+'-catalog.png'),fullPage:true});
                await dialog.locator('.gqp-catalog-result').click();
                assert.equal(await card.locator('[data-field=template_names]').inputValue(),'Linux by Zabbix agent');
                assert.equal(posts.length,priorPosts+2,'Exactly one request per explicit search');
                await card.locator('[data-for-type=templates] .gqp-catalog-open').click();
                await dialog.locator('input').fill('Linux');
                await dialog.locator('.gqp-catalog-search').click();
                await dialog.locator('.gqp-catalog-result').click();
                assert.equal(await card.locator('[data-field=template_names]').inputValue(),'Linux by Zabbix agent','Selection never duplicates a name');
                await row.locator('.gqp-edit-condition').click();
                await condition.locator('.gqp-catalog-open').click();
                await dialog.locator('input').fill('Equipes');
                await dialog.locator('.gqp-catalog-search').click();
                await dialog.locator('.gqp-catalog-result').waitFor();
                await dialog.locator('input').fill('New query');
                assert.equal(await dialog.locator('.gqp-catalog-result').count(),0,'Editing search discards old results');
                await dialog.locator('input').press('Escape');
                assert.equal(await dialog.count(),0,'Escape closes lookup');
                assert.equal(await condition.locator('[data-field=condition_value]').inputValue(),'Equipes','Closing preserves condition');
                assert.equal(await condition.count(),1,'Escape closes only the topmost catalog');
                await condition.locator('.gqp-condition-cancel').click();
                await card.locator('.gqp-preview > button').first().click();
                await card.locator('.gqp-preview-output table').waitFor({timeout:10000}).catch(async e => { throw new Error((await card.locator('.gqp-preview-output').innerText())+'; '+lastResponse+'; '+e.message); });
                assert.equal(await card.locator('.gqp-preview-output table tr').count(),51,'50 real synthetic sample rows plus header');
                assert.ok((await card.locator('.gqp-preview-output').innerText()).includes('251'),'Exact total independent of sample');
                await card.locator('[data-field=title]').fill('Hosts com template Linux');
                assert.equal(await card.locator('.gqp-preview-output').innerText(),'','Edits invalidate preview');
            } else {
                assert.equal(await page.locator('.gav-report-settings').count(),1,'Global settings are a single section');
                assert.equal(await page.locator('.gav-report-settings #gav-data-policy').count(),1,'Policy remains visible with timezone');
                const tech = page.locator('.gav-technology').first();
                await tech.locator(':scope > summary').click();
                const check = tech.locator('.gav-check').first();
                assert.equal(await check.getAttribute('open'),null,'Saved checks start collapsed');
                assert.ok((await tech.locator(':scope > summary').innerText()).includes(name.endsWith('dark') ? '57,14%' : '57.14%'));
                const before = await page.locator('#gav-payload').inputValue();
                await check.locator(':scope > summary').click();
                assert.equal(await page.locator('#gav-payload').inputValue(),before,'Expanding is presentation only');
                await check.locator('.gav-editor-help > summary').click();
                await check.locator('[data-field=age_mode]').selectOption('hour');
                assert.equal(await check.locator('[data-field=max_age]').isVisible(),false);
                await check.locator('[data-field=key]').fill('');
                await check.locator(':scope > summary').click();
                await page.locator('#gav-save').click();
                assert.notEqual(await check.getAttribute('open'),null,'Invalid folded check is revealed');
                assert.equal(posts.length,priorPosts,'Invalid draft cannot be submitted');
                await check.locator('[data-field=key]').fill('icmpping');
                await check.locator('.gav-editor-help > summary').click();
                await page.screenshot({path:path.join(output,name+'-items.png'),fullPage:true});
                await tech.locator('[data-field=source]').selectOption('sla');
                await tech.locator('.gav-sla-import > summary').click();
                await tech.locator('[data-field=sla_url]').fill('http://127.0.0.1:8771/zabbix.php?action=slareport.list&filter_slaid=7&filter_serviceid=42');
                // The harness page is /, so use its same pathname just as the production editor requires.
                await tech.locator('[data-field=sla_url]').fill('http://127.0.0.1:8771/?action=slareport.list&filter_slaid=7&filter_serviceid=42');
                await tech.locator('[data-action=import-sla-url]').click();
                assert.equal(await tech.locator('[data-field=slaid]').inputValue(),'7');
                assert.equal(posts.length,priorPosts,'Editor and URL helper never query the server');
                await tech.locator('[data-field=source]').selectOption('items');
                assert.equal(await check.locator('[data-field=key]').inputValue(),'icmpping');
            }
            await page.screenshot({path:path.join(output,name+'.png'),fullPage:true});
            console.log(name, await page.evaluate(() => ({width:innerWidth,scroll:document.documentElement.scrollWidth,inputs:[...document.querySelectorAll('input[type=text],select')].filter(x=>x.getBoundingClientRect().width>0).slice(0,4).map(x=>getComputedStyle(x).backgroundColor)})));
            await page.setViewportSize({width:700,height:1000});
            assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth + 1), name+' mobile overflow');
            await page.screenshot({path:path.join(output,name+'-mobile.png'),fullPage:true});
            await page.setViewportSize({width:1440,height:1000});
        }
        assert.deepEqual(errors,[]);
        console.log('PASS: local browser editors, PT/EN, light/dark, desktop/mobile. Screenshots: '+output);
    } finally { await browser.close(); }
})().catch(e=>{console.error(e);process.exitCode=1;});
